### PR TITLE
4.9.0 -> 4.10.0

### PR DESCRIPTION
**Pull request by casperdcl**
Also add @lrq3000

### CODE REVIEW

**Comment by casperdcl** [comment]
Hi @pmlandwehr @ocefpaf @jakirkham thanks for merging in #6 and closing #7, #8.

I don't think you quite understood what I meant in the discussion in #6... I wanted write access to this repo, so that I can
- merge [tqdm/tqdm-feedstock](https://github.com/tqdm/tqdm-feedstock/) into [conda-forge/tqdm-feedstock](https://github.com/conda-forge/tqdm-feedstock/) myself;
- add other maintainers from the tqdm team as and when required.

Nothing to do with what appears in `recipe/meta.yaml`. Unless you're telling me you have some sort of bot which periodically updates repository access permissions using the `meta.yaml` file...

**Comment by ocefpaf** [comment]
> . Unless you're telling me you have some sort of bot which periodically updates repository access permissions using the `meta.yaml` file...

That is exactly it. We (conda-forge) cannot handle the number of feedstocks manually, so we automate that. If you add a username you will be given merge rights here to a feedstock, and the opposite when you remove it.

**Comment by casperdcl** [comment]
Nice! I'll wait until I get access then and merge this in myself. Presumably it'll take less than 24 hours.

**Comment by jakirkham** [comment]
The bot runs once every 24 hrs. Assuming no issues it should add you.

We have been discussing an on-demand service ( https://github.com/conda-forge/conda-forge-webservices/issues/63 ) that would add people any time there is a push to the feedstock, but that will require a rewrite of the existing service.

**Comment by lrq3000** [comment]
:-D

About the 24h delay, I think it's a good protection against bot, and 24h is not such a long wait to add permissions (it's only a one-time process), so your system is working good enough for me ;)

**Comment by casperdcl** [comment]
Hi @pmlandwehr @ocefpaf @jakirkham do any of you know why the version badge seems to be one version too old? https://anaconda.org/conda-forge/tqdm/badges is showing as 4.9.0 even though the [main label](https://anaconda.org/conda-forge/tqdm/labels) is 4.10.0. This issue also existed with previous versions. It would also be great if the badge url https://anaconda.org/conda-forge/tqdm/badges/version.svg supported styling or at least defaulted to shields.io recommended "flat", i.e. https://anaconda.org/conda-forge/tqdm/badges/version.svg?style=flat. At the moment it redirects to https://img.shields.io/badge/Anaconda%20Cloud-4.9.0-blue.svg?style=flat-square

**Comment by pmlandwehr** [comment]
No - I've noticed version lags on badges across the different repos, but lack any good explanation for it.

**Comment by casperdcl** [comment]
Badge version still hasn't been updated since 4.9.0. Doesn't look good when next to the pypi version badge - sort of prompts people to not use conda.

**Comment by pmlandwehr** [comment]
Yeah - seems like a note for @msarahan? The issue seems to be on anaconda.org's end…

**Comment by msarahan** [comment]
I am not on that team and cannot help you.  Please use the official support channels: https://github.com/Anaconda-Platform/support

**Comment by jakirkham** [comment]
FYI this is the relevant issue ( https://github.com/Anaconda-Platform/support/issues/7 ).

**Comment by casperdcl** [comment]
Thanks for the follow-up. Have lots of other work to deal with currently; haven't been paying much attention here. Cheers

**Pull request merged**
