### PR TITLE
Please make the package arch dependent again

### PR DESCRIPTION
**Pull request by hmaarrfk**
xref: https://github.com/conda-forge/miniforge/pull/2

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

This helps make conda distributions without conda-constructor 3

**Comment by casperdcl** [comment]
@hadim can you confirm this is required?

Also is conda coming to aarch64? That would be great. I've loathed managing with venvs on my phone...

**Comment by hmaarrfk** [comment]
I think this is the fastest way to get a conda installer on aarch64. @hadim is working on the other method, and he has made the necessary PRs, but this is definitely a quicker shortcut to take.

**Comment by casperdcl** [comment]
I was referring to https://github.com/conda/conda/issues/8297

**Comment by hmaarrfk** [comment]
See miniforge link. We will likely get stuck on a few packages along the way, but it should come out soonish.

**Comment by hadim** [comment]
I am not sure this was needed since the other PRs will solve it but it's definitively a shortcut to get miniforge working.

 I think we should set back tqdm to `noarch` once it's possible.

I'll take care of it @casperdcl.

**Pull request merged**
